/**
 * Writes public/sitemap.xml and public/robots.txt from src/content/pages.json.
 *
 * Runs automatically before every build (see the "prebuild" script in
 * package.json), so a page added to pages.json cannot be forgotten here.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const config = JSON.parse(readFileSync(resolve(root, "src/content/pages.json"), "utf8"));

const siteUrl = (process.env.SITE_URL || config.siteUrl).replace(/\/$/, "");

if (siteUrl.includes("REPLACE-WITH-YOUR-DOMAIN")) {
  console.warn(
    "\n  ⚠  sitemap: siteUrl is still a placeholder.\n" +
      "     Set it in src/content/pages.json (or pass SITE_URL=...) before you deploy,\n" +
      "     or search engines will be given URLs on a domain that does not exist.\n",
  );
}

const today = new Date().toISOString().slice(0, 10);
const pages = config.sections.flatMap((section) => section.pages);

const urls = pages
  .map(
    (page) =>
      `  <url>\n` +
      `    <loc>${siteUrl}${page.path === "/" ? "/" : page.path}</loc>\n` +
      `    <lastmod>${today}</lastmod>\n` +
      `    <priority>${page.priority}</priority>\n` +
      `  </url>`,
  )
  .join("\n");

writeFileSync(
  resolve(root, "public/sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
);

writeFileSync(
  resolve(root, "public/robots.txt"),
  [
    "# Generated by scripts/generate-sitemap.mjs. Do not edit by hand.",
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${siteUrl}/sitemap.xml`,
    "",
  ].join("\n"),
);

console.log(`  ✓ sitemap.xml and robots.txt written — ${pages.length} pages`);
